const lostopfColors = {
  "Turm/Insel/Keil/Kopf-Bahnhöfe": "#1f77b4",
  "Bhf-Paare": "#ff7f0e",
  "Essen+Trinken/Eisdiele": "#2ca02c",
  "Ehemalige FV-Bahnhöfe": "#d62728",
  "Eisenbahnmuseum": "#9467bd",
  "Frankfurt & Rhein-Main-Region": "#8c564b",
  "Kleine Hochschulorte": "#e377c2",
  "Hanse/Meer/Küste/Deich": "#7f7f7f",
  "Kranke Ortsnamen": "#bcbd22",
  "Münster Stadt & Umland/Fahrrad": "#17becf",
  "Mini-Golf in Mini-Städten": "#4c78a8",
  "Natur/Wanderbahnhöfe": "#f58518",
  "Partnerstädte": "#54a24b",
  "Rangierbahnhöfe": "#e45756",
  "Tatort": "#b279a2",
  "Unter Tage": "#9d755d",
  "Wunschlos": "#ff9da6",
  "Weltkulturerbe": "#bab0ab",
  "Unbekannt": "#7f7f7f"
};

const coordinates = [
  {
    "id": "BP-2a",
    "bahnhof": "Schwaig",
    "zeitbedarf": null,
    "distanz": null,
    "punkte_bahnhof": 3,
    "punkte_aufgabe": 0,
    "punkte_bonus": 0,
    "aufgabe": "Bhf Paar mit Schweighofen\n",
    "lostopf": "Bhf-Paare",
    "latitude": 49.471494,
    "longitude": 11.200442,
    "latitude2": null,
    "longitude2": null
  },
  {
    "id": "BP-2b",
    "bahnhof": "Schweighofen",
    "zeitbedarf": null,
    "distanz": null,
    "punkte_bahnhof": 4,
    "punkte_aufgabe": 0,
    "punkte_bonus": 0,
    "aufgabe": "Bhf Paar mit Schwaig\n",
    "lostopf": "Bhf-Paare",
    "latitude": 49.032686,
    "longitude": 7.999224,
    "latitude2": null,
    "longitude2": null
  },
  {
    "id": "BP-5a",
    "bahnhof": "Regensburg Hbf",
    "zeitbedarf": null,
    "distanz": null,
    "punkte_bahnhof": 5,
    "punkte_aufgabe": 0,
    "punkte_bonus": 0,
    "aufgabe": "Bhf Paar mit Sonneberg(Thür)Hbf\n",
    "lostopf": "Bhf-Paare",
    "latitude": 49.011672,
    "longitude": 12.099617,
    "latitude2": 49.012615,
    "longitude2": 12.099008
  },
  {
    "id": "BP-5b",
    "bahnhof": "Sonneberg(Thür)Hbf",
    "zeitbedarf": null,
    "distanz": null,
    "punkte_bahnhof": 6,
    "punkte_aufgabe": 0,
    "punkte_bonus": 0,
    "aufgabe": "Bhf Paar mit Regensburg Hbf\n",
    "lostopf": "Bhf-Paare",
    "latitude": 50.355078,
    "longitude": 11.168848,
    "latitude2": 50.355845,
    "longitude2": 11.168742
  },
  {
    "id": "BP-11a",
    "bahnhof": "Herzberg(Harz)",
    "zeitbedarf": null,
    "distanz": null,
    "punkte_bahnhof": 7,
    "punkte_aufgabe": 0,
    "punkte_bonus": 0,
    "aufgabe": "Bhf Paar mit Nierstein\n",
    "lostopf": "Bhf-Paare",
    "latitude": 51.643861,
    "longitude": 10.329923,
    "latitude2": null,
    "longitude2": null
  },
  {
    "id": "BP-11b",
    "bahnhof": "Nierstein",
    "zeitbedarf": null,
    "distanz": null,
    "punkte_bahnhof": 8,
    "punkte_aufgabe": 0,
    "punkte_bonus": 0,
    "aufgabe": "Bhf Paar mit Herzberg(Harz)\n",
    "lostopf": "Bhf-Paare",
    "latitude": 49.872002,
    "longitude": 8.34281,
    "latitude2": null,
    "longitude2": null
  },
  {
    "id": "BP-24a",
    "bahnhof": null,
    "zeitbedarf": null,
    "distanz": null,
    "punkte_bahnhof": 9,
    "punkte_aufgabe": 0,
    "punkte_bonus": 0,
    "aufgabe": null,
    "lostopf": "Bhf-Paare",
    "latitude": 49.436253,
    "longitude": 7.768677,
    "latitude2": null,
    "longitude2": null
  },
  {
    "id": "BP-24b",
    "bahnhof": null,
    "zeitbedarf": null,
    "distanz": null,
    "punkte_bahnhof": 10,
    "punkte_aufgabe": 0,
    "punkte_bonus": 0,
    "aufgabe": null,
    "lostopf": "Bhf-Paare",
    "latitude": 50.177917,
    "longitude": 8.46898,
    "latitude2": null,
    "longitude2": null
  },
  {
    "id": "BP-26a",
    "bahnhof": null,
    "zeitbedarf": null,
    "distanz": null,
    "punkte_bahnhof": 13,
    "punkte_aufgabe": 0,
    "punkte_bonus": 0,
    "aufgabe": null,
    "lostopf": "Bhf-Paare",
    "latitude": 51.042262,
    "longitude": 14.480583,
    "latitude2": null,
    "longitude2": null
  },
  {
    "id": "BP-26b",
    "bahnhof": null,
    "zeitbedarf": null,
    "distanz": null,
    "punkte_bahnhof": 14,
    "punkte_aufgabe": 0,
    "punkte_bonus": 0,
    "aufgabe": null,
    "lostopf": "Bhf-Paare",
    "latitude": 52.435672,
    "longitude": 13.540246,
    "latitude2": null,
    "longitude2": null
  },
  {
    "id": "BP-31a",
    "bahnhof": null,
    "zeitbedarf": null,
    "distanz": null,
    "punkte_bahnhof": 15,
    "punkte_aufgabe": 0,
    "punkte_bonus": 0,
    "aufgabe": null,
    "lostopf": "Bhf-Paare",
    "latitude": 51.477188,
    "longitude": 11.987518,
    "latitude2": null,
    "longitude2": null
  },
  {
    "id": "BP-31b",
    "bahnhof": null,
    "zeitbedarf": null,
    "distanz": null,
    "punkte_bahnhof": 16,
    "punkte_aufgabe": 0,
    "punkte_bonus": 0,
    "aufgabe": null,
    "lostopf": "Bhf-Paare",
    "latitude": 52.057227,
    "longitude": 8.35771,
    "latitude2": null,
    "longitude2": null
  },
  {
    "id": "BP-32a",
    "bahnhof": null,
    "zeitbedarf": null,
    "distanz": null,
    "punkte_bahnhof": 17,
    "punkte_aufgabe": 0,
    "punkte_bonus": 0,
    "aufgabe": null,
    "lostopf": "Bhf-Paare",
    "latitude": 52.969922,
    "longitude": 10.552857,
    "latitude2": null,
    "longitude2": null
  },
  {
    "id": "BP-32b",
    "bahnhof": null,
    "zeitbedarf": null,
    "distanz": null,
    "punkte_bahnhof": 18,
    "punkte_aufgabe": 0,
    "punkte_bonus": 0,
    "aufgabe": null,
    "lostopf": "Bhf-Paare",
    "latitude": 48.710222,
    "longitude": 9.41626,
    "latitude2": null,
    "longitude2": null
  },
  {
    "id": "BP-40a",
    "bahnhof": null,
    "zeitbedarf": null,
    "distanz": null,
    "punkte_bahnhof": 21,
    "punkte_aufgabe": 0,
    "punkte_bonus": 0,
    "aufgabe": null,
    "lostopf": "Bhf-Paare",
    "latitude": 53.911237,
    "longitude": 10.734885,
    "latitude2": null,
    "longitude2": null
  },
  {
    "id": "BP-40b",
    "bahnhof": null,
    "zeitbedarf": null,
    "distanz": null,
    "punkte_bahnhof": 22,
    "punkte_aufgabe": 0,
    "punkte_bonus": 0,
    "aufgabe": null,
    "lostopf": "Bhf-Paare",
    "latitude": 51.217327,
    "longitude": 6.629644,
    "latitude2": null,
    "longitude2": null
  },
  {
    "id": "P-10a",
    "bahnhof": null,
    "zeitbedarf": null,
    "distanz": null,
    "punkte_bahnhof": 25,
    "punkte_aufgabe": 0,
    "punkte_bonus": 0,
    "aufgabe": null,
    "lostopf": "Partnerstädte",
    "latitude": 49.454213,
    "longitude": 11.070849,
    "latitude2": null,
    "longitude2": null
  },
  {
    "id": "P-10b",
    "bahnhof": null,
    "zeitbedarf": null,
    "distanz": null,
    "punkte_bahnhof": 26,
    "punkte_aufgabe": 0,
    "punkte_bonus": 0,
    "aufgabe": null,
    "lostopf": "Partnerstädte",
    "latitude": 50.883063,
    "longitude": 12.057639,
    "latitude2": null,
    "longitude2": null
  },
  {
    "id": "P-16a",
    "bahnhof": null,
    "zeitbedarf": null,
    "distanz": null,
    "punkte_bahnhof": 27,
    "punkte_aufgabe": 0,
    "punkte_bonus": 0,
    "aufgabe": null,
    "lostopf": "Partnerstädte",
    "latitude": 54.193438,
    "longitude": 9.10093,
    "latitude2": null,
    "longitude2": null
  },
  {
    "id": "P-16b",
    "bahnhof": null,
    "zeitbedarf": null,
    "distanz": null,
    "punkte_bahnhof": 28,
    "punkte_aufgabe": 0,
    "punkte_bonus": 0,
    "aufgabe": null,
    "lostopf": "Partnerstädte",
    "latitude": 53.856027,
    "longitude": 13.701789,
    "latitude2": null,
    "longitude2": null
  },
  {
    "id": "P-31a",
    "bahnhof": null,
    "zeitbedarf": null,
    "distanz": null,
    "punkte_bahnhof": 31,
    "punkte_aufgabe": 0,
    "punkte_bonus": 0,
    "aufgabe": null,
    "lostopf": "Partnerstädte",
    "latitude": 51.054434,
    "longitude": 8.78942,
    "latitude2": null,
    "longitude2": null
  },
  {
    "id": "P-31b",
    "bahnhof": null,
    "zeitbedarf": null,
    "distanz": null,
    "punkte_bahnhof": 32,
    "punkte_aufgabe": 0,
    "punkte_bonus": 0,
    "aufgabe": null,
    "lostopf": "Partnerstädte",
    "latitude": 50.9112,
    "longitude": 13.043289,
    "latitude2": null,
    "longitude2": null
  },
  {
    "id": "P-36a",
    "bahnhof": null,
    "zeitbedarf": null,
    "distanz": null,
    "punkte_bahnhof": 35,
    "punkte_aufgabe": 0,
    "punkte_bonus": 0,
    "aufgabe": null,
    "lostopf": "Partnerstädte",
    "latitude": 53.002456,
    "longitude": 11.762482,
    "latitude2": null,
    "longitude2": null
  },
  {
    "id": "P-36b",
    "bahnhof": null,
    "zeitbedarf": null,
    "distanz": null,
    "punkte_bahnhof": 36,
    "punkte_aufgabe": 0,
    "punkte_bonus": 0,
    "aufgabe": null,
    "lostopf": "Partnerstädte",
    "latitude": 53.75453,
    "longitude": 9.659152,
    "latitude2": null,
    "longitude2": null
  },
  {
    "id": "P-39a",
    "bahnhof": null,
    "zeitbedarf": null,
    "distanz": null,
    "punkte_bahnhof": 37,
    "punkte_aufgabe": 0,
    "punkte_bonus": 0,
    "aufgabe": null,
    "lostopf": "Partnerstädte",
    "latitude": 50.835115,
    "longitude": 10.951666,
    "latitude2": null,
    "longitude2": null
  },
  {
    "id": "P-39b",
    "bahnhof": null,
    "zeitbedarf": null,
    "distanz": null,
    "punkte_bahnhof": 38,
    "punkte_aufgabe": 0,
    "punkte_bonus": 0,
    "aufgabe": null,
    "lostopf": "Partnerstädte",
    "latitude": 51.311971,
    "longitude": 9.448129,
    "latitude2": null,
    "longitude2": null
  },
  {
    "id": "EB-1",
    "bahnhof": null,
    "zeitbedarf": null,
    "distanz": null,
    "punkte_bahnhof": 39,
    "punkte_aufgabe": 0,
    "punkte_bonus": 0,
    "aufgabe": null,
    "lostopf": "Ehemalige FV-Bahnhöfe",
    "latitude": 48.516138,
    "longitude": 9.055184,
    "latitude2": null,
    "longitude2": null
  },
  {
    "id": "EB-3",
    "bahnhof": null,
    "zeitbedarf": null,
    "distanz": null,
    "punkte_bahnhof": 40,
    "punkte_aufgabe": 0,
    "punkte_bonus": 0,
    "aufgabe": null,
    "lostopf": "Ehemalige FV-Bahnhöfe",
    "latitude": 52.535092,
    "longitude": 13.390183,
    "latitude2": null,
    "longitude2": null
  },
  {
    "id": "EB-7",
    "bahnhof": null,
    "zeitbedarf": null,
    "distanz": null,
    "punkte_bahnhof": 41,
    "punkte_aufgabe": 0,
    "punkte_bonus": 0,
    "aufgabe": null,
    "lostopf": "Ehemalige FV-Bahnhöfe",
    "latitude": 47.479412,
    "longitude": 11.239749,
    "latitude2": null,
    "longitude2": null
  },
  {
    "id": "EB-10",
    "bahnhof": null,
    "zeitbedarf": null,
    "distanz": null,
    "punkte_bahnhof": 42,
    "punkte_aufgabe": 0,
    "punkte_bonus": 0,
    "aufgabe": null,
    "lostopf": "Ehemalige FV-Bahnhöfe",
    "latitude": 51.550914,
    "longitude": 7.682614,
    "latitude2": null,
    "longitude2": null
  },
  {
    "id": "EB-11",
    "bahnhof": null,
    "zeitbedarf": null,
    "distanz": null,
    "punkte_bahnhof": 43,
    "punkte_aufgabe": 0,
    "punkte_bonus": 0,
    "aufgabe": null,
    "lostopf": "Ehemalige FV-Bahnhöfe",
    "latitude": 51.983965,
    "longitude": 9.809597,
    "latitude2": null,
    "longitude2": null
  },
  {
    "id": "EB-12",
    "bahnhof": null,
    "zeitbedarf": null,
    "distanz": null,
    "punkte_bahnhof": 44,
    "punkte_aufgabe": 0,
    "punkte_bonus": 0,
    "aufgabe": null,
    "lostopf": "Ehemalige FV-Bahnhöfe",
    "latitude": 49.959394,
    "longitude": 11.579481,
    "latitude2": null,
    "longitude2": null
  },
  {
    "id": "EB-16",
    "bahnhof": null,
    "zeitbedarf": null,
    "distanz": null,
    "punkte_bahnhof": 45,
    "punkte_aufgabe": 0,
    "punkte_bonus": 0,
    "aufgabe": null,
    "lostopf": "Ehemalige FV-Bahnhöfe",
    "latitude": 51.906117,
    "longitude": 10.429386,
    "latitude2": null,
    "longitude2": null
  },
  {
    "id": "EB-17",
    "bahnhof": null,
    "zeitbedarf": null,
    "distanz": null,
    "punkte_bahnhof": 46,
    "punkte_aufgabe": 0,
    "punkte_bonus": 0,
    "aufgabe": null,
    "lostopf": "Ehemalige FV-Bahnhöfe",
    "latitude": 51.10113,
    "longitude": 8.070652,
    "latitude2": null,
    "longitude2": null
  },
  {
    "id": "EB-18",
    "bahnhof": null,
    "zeitbedarf": null,
    "distanz": null,
    "punkte_bahnhof": 47,
    "punkte_aufgabe": 0,
    "punkte_bonus": 0,
    "aufgabe": null,
    "lostopf": "Ehemalige FV-Bahnhöfe",
    "latitude": 51.732534,
    "longitude": 14.660665,
    "latitude2": null,
    "longitude2": null
  },
  {
    "id": "EB-23",
    "bahnhof": null,
    "zeitbedarf": null,
    "distanz": null,
    "punkte_bahnhof": 48,
    "punkte_aufgabe": 0,
    "punkte_bonus": 0,
    "aufgabe": null,
    "lostopf": "Ehemalige FV-Bahnhöfe",
    "latitude": 50.874102,
    "longitude": 8.01766,
    "latitude2": null,
    "longitude2": null
  },
  {
    "id": "EB-25",
    "bahnhof": null,
    "zeitbedarf": null,
    "distanz": null,
    "punkte_bahnhof": 49,
    "punkte_aufgabe": 0,
    "punkte_bonus": 0,
    "aufgabe": null,
    "lostopf": "Ehemalige FV-Bahnhöfe",
    "latitude": 53.809475,
    "longitude": 10.37737,
    "latitude2": null,
    "longitude2": null
  },
  {
    "id": "E-2",
    "bahnhof": null,
    "zeitbedarf": null,
    "distanz": null,
    "punkte_bahnhof": 50,
    "punkte_aufgabe": 0,
    "punkte_bonus": 0,
    "aufgabe": null,
    "lostopf": "Essen+Trinken/Eisdiele",
    "latitude": 50.141516,
    "longitude": 8.5665,
    "latitude2": null,
    "longitude2": null
  },
  {
    "id": "E-10",
    "bahnhof": null,
    "zeitbedarf": null,
    "distanz": null,
    "punkte_bahnhof": 51,
    "punkte_aufgabe": 0,
    "punkte_bonus": 0,
    "aufgabe": null,
    "lostopf": "Essen+Trinken/Eisdiele",
    "latitude": 50.938715,
    "longitude": 6.974353,
    "latitude2": null,
    "longitude2": null
  },
  {
    "id": "E-11",
    "bahnhof": null,
    "zeitbedarf": null,
    "distanz": null,
    "punkte_bahnhof": 52,
    "punkte_aufgabe": 0,
    "punkte_bonus": 0,
    "aufgabe": null,
    "lostopf": "Essen+Trinken/Eisdiele",
    "latitude": 52.022228,
    "longitude": 8.529231,
    "latitude2": null,
    "longitude2": null
  },
  {
    "id": "E-14",
    "bahnhof": null,
    "zeitbedarf": null,
    "distanz": null,
    "punkte_bahnhof": 53,
    "punkte_aufgabe": 0,
    "punkte_bonus": 0,
    "aufgabe": null,
    "lostopf": "Essen+Trinken/Eisdiele",
    "latitude": 50.105252,
    "longitude": 8.691505,
    "latitude2": null,
    "longitude2": null
  },
  {
    "id": "E-17",
    "bahnhof": null,
    "zeitbedarf": null,
    "distanz": null,
    "punkte_bahnhof": 54,
    "punkte_aufgabe": 0,
    "punkte_bonus": 0,
    "aufgabe": null,
    "lostopf": "Essen+Trinken/Eisdiele",
    "latitude": 50.086323,
    "longitude": 8.242165,
    "latitude2": null,
    "longitude2": null
  },
  {
    "id": "E-18",
    "bahnhof": null,
    "zeitbedarf": null,
    "distanz": null,
    "punkte_bahnhof": 55,
    "punkte_aufgabe": 0,
    "punkte_bonus": 0,
    "aufgabe": null,
    "lostopf": "Essen+Trinken/Eisdiele",
    "latitude": 53.553509,
    "longitude": 9.993047,
    "latitude2": null,
    "longitude2": null
  },
  {
    "id": "E-21",
    "bahnhof": null,
    "zeitbedarf": null,
    "distanz": null,
    "punkte_bahnhof": 56,
    "punkte_aufgabe": 0,
    "punkte_bonus": 0,
    "aufgabe": null,
    "lostopf": "Essen+Trinken/Eisdiele",
    "latitude": 50.772404,
    "longitude": 6.080204,
    "latitude2": null,
    "longitude2": null
  },
  {
    "id": "E-22",
    "bahnhof": null,
    "zeitbedarf": null,
    "distanz": null,
    "punkte_bahnhof": 57,
    "punkte_aufgabe": 0,
    "punkte_bonus": 0,
    "aufgabe": null,
    "lostopf": "Essen+Trinken/Eisdiele",
    "latitude": 49.47388,
    "longitude": 8.469134,
    "latitude2": null,
    "longitude2": null
  },
  {
    "id": "E-23",
    "bahnhof": null,
    "zeitbedarf": null,
    "distanz": null,
    "punkte_bahnhof": 58,
    "punkte_aufgabe": 0,
    "punkte_bonus": 0,
    "aufgabe": null,
    "lostopf": "Essen+Trinken/Eisdiele",
    "latitude": 53.549733,
    "longitude": 9.960524,
    "latitude2": null,
    "longitude2": null
  },
  {
    "id": "E-25",
    "bahnhof": null,
    "zeitbedarf": null,
    "distanz": null,
    "punkte_bahnhof": 59,
    "punkte_aufgabe": 0,
    "punkte_bonus": 0,
    "aufgabe": null,
    "lostopf": "Essen+Trinken/Eisdiele",
    "latitude": 51.238166,
    "longitude": 6.779768,
    "latitude2": null,
    "longitude2": null
  },
  {
    "id": "F-1",
    "bahnhof": "Bad Homburg",
    "zeitbedarf": 21,
    "distanz": 0.8,
    "punkte_bahnhof": 60,
    "punkte_aufgabe": 35,
    "punkte_bonus": null,
    "aufgabe": "Genießt die Schöne Aussicht und macht ein Teamfoto\n",
    "lostopf": "Frankfurt & Rhein-Main-Region",
    "latitude": 50.219904,
    "longitude": 8.620624,
    "latitude2": 50.223555,
    "longitude2": 8.621756
  },
  {
    "id": "F-4",
    "bahnhof": "Bad Nauheim",
    "zeitbedarf": 17,
    "distanz": 0.5,
    "punkte_bahnhof": 61,
    "punkte_aufgabe": 30,
    "punkte_bonus": null,
    "aufgabe": "Foto an einem der beiden Sprudel im Sprudelhof\nDer Sprudelhof ist eine Kuranlage in Bad Nauheim, welche zwischen 1905 und 1911 im Jugendstil entstand. Er gilt zusammen als ein hervorragendes Beispiel dieses Stils und ist zugleich eines der gelungensten und geschlossensten Bauwerke dieser Epoche. ",
    "lostopf": "Frankfurt & Rhein-Main-Region",
    "latitude": 50.367904,
    "longitude": 8.749334,
    "latitude2": 50.367455,
    "longitude2": 8.743555
  },
  {
    "id": "F-5",
    "bahnhof": "Dietzenbach Mitte",
    "zeitbedarf": 17,
    "distanz": 0.6,
    "punkte_bahnhof": 62,
    "punkte_aufgabe": 30,
    "punkte_bonus": null,
    "aufgabe": "Foto mit SkulpTouren Park - Stillleben\n",
    "lostopf": "Frankfurt & Rhein-Main-Region",
    "latitude": 50.01766,
    "longitude": 8.789218,
    "latitude2": 50.019755,
    "longitude2": 8.784356
  },
  {
    "id": "F-7",
    "bahnhof": "Wiesbaden Hbf",
    "zeitbedarf": 49,
    "distanz": 1.9,
    "punkte_bahnhof": 63,
    "punkte_aufgabe": 75,
    "punkte_bonus": null,
    "aufgabe": "Foto vor der Spielbank Wiesbaden\n",
    "lostopf": "Frankfurt & Rhein-Main-Region",
    "latitude": 50.070791,
    "longitude": 8.243731,
    "latitude2": 50.084855,
    "longitude2": 8.246956
  },
  {
    "id": "F-9",
    "bahnhof": "Idstein(Taunus)",
    "zeitbedarf": 37,
    "distanz": 1.2,
    "punkte_bahnhof": 64,
    "punkte_aufgabe": 60,
    "punkte_bonus": 10,
    "aufgabe": "Foto vor dem Hexenturm. Bonus: Findet eine Hexe und macht ein Foto mit ihr.\nWir sind nicht mehr im Mittelalter, demnach ist Folter keinea adäquate Methode mehr um das Geständnis einer verdächtigen Hexe zu erhalten.",
    "lostopf": "Frankfurt & Rhein-Main-Region",
    "latitude": 50.21599,
    "longitude": 8.257264,
    "latitude2": 50.222202,
    "longitude2": 8.268604
  },
  {
    "id": "F-13",
    "bahnhof": "Limburg(Lahn) Bahnhof/Südseite",
    "zeitbedarf": 23,
    "distanz": 0.7,
    "punkte_bahnhof": 65,
    "punkte_aufgabe": 40,
    "punkte_bonus": 10,
    "aufgabe": "Genießt die Schöne Aussicht auf das Lahntal. Bonus: Foto vom Museum, in dem sich die \"goldene Badewanne\" befindet.\nDer Bus LM5 von Limburg (Süd) nach Limburg (Lahn) ist im FV-Ticket inkludiert.",
    "lostopf": "Frankfurt & Rhein-Main-Region",
    "latitude": 50.389155,
    "longitude": 8.067555,
    "latitude2": null,
    "longitude2": null
  },
  {
    "id": "F-20",
    "bahnhof": null,
    "zeitbedarf": null,
    "distanz": null,
    "punkte_bahnhof": 66,
    "punkte_aufgabe": 0,
    "punkte_bonus": 0,
    "aufgabe": null,
    "lostopf": "Frankfurt & Rhein-Main-Region",
    "latitude": 50.10306,
    "longitude": 8.685161,
    "latitude2": null,
    "longitude2": null
  },
  {
    "id": "F-23",
    "bahnhof": null,
    "zeitbedarf": null,
    "distanz": null,
    "punkte_bahnhof": 67,
    "punkte_aufgabe": 0,
    "punkte_bonus": 0,
    "aufgabe": null,
    "lostopf": "Frankfurt & Rhein-Main-Region",
    "latitude": 50.130842,
    "longitude": 8.756596,
    "latitude2": null,
    "longitude2": null
  },
  {
    "id": "F-25",
    "bahnhof": null,
    "zeitbedarf": null,
    "distanz": null,
    "punkte_bahnhof": 68,
    "punkte_aufgabe": 0,
    "punkte_bonus": 0,
    "aufgabe": null,
    "lostopf": "Frankfurt & Rhein-Main-Region",
    "latitude": 50.32208,
    "longitude": 8.747313,
    "latitude2": null,
    "longitude2": null
  },
  {
    "id": "H-1",
    "bahnhof": null,
    "zeitbedarf": null,
    "distanz": null,
    "punkte_bahnhof": 69,
    "punkte_aufgabe": 0,
    "punkte_bonus": 0,
    "aufgabe": null,
    "lostopf": "Kleine Hochschulorte",
    "latitude": 52.048221,
    "longitude": 10.371587,
    "latitude2": null,
    "longitude2": null
  },
  {
    "id": "H-2",
    "bahnhof": null,
    "zeitbedarf": null,
    "distanz": null,
    "punkte_bahnhof": 70,
    "punkte_aufgabe": 0,
    "punkte_bonus": 0,
    "aufgabe": null,
    "lostopf": "Kleine Hochschulorte",
    "latitude": 51.82721,
    "longitude": 9.45092,
    "latitude2": null,
    "longitude2": null
  },
  {
    "id": "H-3",
    "bahnhof": null,
    "zeitbedarf": null,
    "distanz": null,
    "punkte_bahnhof": 71,
    "punkte_aufgabe": 0,
    "punkte_bonus": 0,
    "aufgabe": null,
    "lostopf": "Kleine Hochschulorte",
    "latitude": 50.401625,
    "longitude": 7.626797,
    "latitude2": null,
    "longitude2": null
  },
  {
    "id": "H-4",
    "bahnhof": null,
    "zeitbedarf": null,
    "distanz": null,
    "punkte_bahnhof": 72,
    "punkte_aufgabe": 0,
    "punkte_bonus": 0,
    "aufgabe": null,
    "lostopf": "Kleine Hochschulorte",
    "latitude": 52.318206,
    "longitude": 13.632312,
    "latitude2": null,
    "longitude2": null
  },
  {
    "id": "H-6",
    "bahnhof": null,
    "zeitbedarf": null,
    "distanz": null,
    "punkte_bahnhof": 73,
    "punkte_aufgabe": 0,
    "punkte_bonus": 0,
    "aufgabe": null,
    "lostopf": "Kleine Hochschulorte",
    "latitude": 51.349949,
    "longitude": 9.855173,
    "latitude2": null,
    "longitude2": null
  },
  {
    "id": "H-8",
    "bahnhof": null,
    "zeitbedarf": null,
    "distanz": null,
    "punkte_bahnhof": 74,
    "punkte_aufgabe": 0,
    "punkte_bonus": 0,
    "aufgabe": null,
    "lostopf": "Kleine Hochschulorte",
    "latitude": 48.153451,
    "longitude": 9.475028,
    "latitude2": null,
    "longitude2": null
  },
  {
    "id": "H-9",
    "bahnhof": null,
    "zeitbedarf": null,
    "distanz": null,
    "punkte_bahnhof": 75,
    "punkte_aufgabe": 0,
    "punkte_bonus": 0,
    "aufgabe": null,
    "lostopf": "Kleine Hochschulorte",
    "latitude": 52.540705,
    "longitude": 13.002413,
    "latitude2": null,
    "longitude2": null
  },
  {
    "id": "H-15",
    "bahnhof": null,
    "zeitbedarf": null,
    "distanz": null,
    "punkte_bahnhof": 76,
    "punkte_aufgabe": 0,
    "punkte_bonus": 0,
    "aufgabe": null,
    "lostopf": "Kleine Hochschulorte",
    "latitude": 49.98846,
    "longitude": 7.962486,
    "latitude2": null,
    "longitude2": null
  },
  {
    "id": "H-20",
    "bahnhof": null,
    "zeitbedarf": null,
    "distanz": null,
    "punkte_bahnhof": 77,
    "punkte_aufgabe": 0,
    "punkte_bonus": 0,
    "aufgabe": null,
    "lostopf": "Kleine Hochschulorte",
    "latitude": 49.60764,
    "longitude": 7.168789,
    "latitude2": null,
    "longitude2": null
  },
  {
    "id": "H-22",
    "bahnhof": null,
    "zeitbedarf": null,
    "distanz": null,
    "punkte_bahnhof": 78,
    "punkte_aufgabe": 0,
    "punkte_bonus": 0,
    "aufgabe": null,
    "lostopf": "Kleine Hochschulorte",
    "latitude": 48.404205,
    "longitude": 8.01683,
    "latitude2": null,
    "longitude2": null
  },
  {
    "id": "HM-1",
    "bahnhof": null,
    "zeitbedarf": null,
    "distanz": null,
    "punkte_bahnhof": 79,
    "punkte_aufgabe": 0,
    "punkte_bonus": 0,
    "aufgabe": null,
    "lostopf": "Hanse/Meer/Küste/Deich",
    "latitude": 53.892441,
    "longitude": 11.462035,
    "latitude2": null,
    "longitude2": null
  },
  {
    "id": "HM-3",
    "bahnhof": null,
    "zeitbedarf": null,
    "distanz": null,
    "punkte_bahnhof": 80,
    "punkte_aufgabe": 0,
    "punkte_bonus": 0,
    "aufgabe": null,
    "lostopf": "Hanse/Meer/Küste/Deich",
    "latitude": 51.57193,
    "longitude": 8.106754,
    "latitude2": null,
    "longitude2": null
  },
  {
    "id": "HM-6",
    "bahnhof": null,
    "zeitbedarf": null,
    "distanz": null,
    "punkte_bahnhof": 81,
    "punkte_aufgabe": 0,
    "punkte_bonus": 0,
    "aufgabe": null,
    "lostopf": "Hanse/Meer/Küste/Deich",
    "latitude": 52.124803,
    "longitude": 11.633467,
    "latitude2": null,
    "longitude2": null
  },
  {
    "id": "HM-9",
    "bahnhof": null,
    "zeitbedarf": null,
    "distanz": null,
    "punkte_bahnhof": 82,
    "punkte_aufgabe": 0,
    "punkte_bonus": 0,
    "aufgabe": null,
    "lostopf": "Hanse/Meer/Küste/Deich",
    "latitude": 54.18327,
    "longitude": 12.084485,
    "latitude2": null,
    "longitude2": null
  },
  {
    "id": "HM-10",
    "bahnhof": null,
    "zeitbedarf": null,
    "distanz": null,
    "punkte_bahnhof": 83,
    "punkte_aufgabe": 0,
    "punkte_bonus": 0,
    "aufgabe": null,
    "lostopf": "Hanse/Meer/Küste/Deich",
    "latitude": 53.072508,
    "longitude": 8.809627,
    "latitude2": null,
    "longitude2": null
  },
  {
    "id": "HM-11",
    "bahnhof": null,
    "zeitbedarf": null,
    "distanz": null,
    "punkte_bahnhof": 84,
    "punkte_aufgabe": 0,
    "punkte_bonus": 0,
    "aufgabe": null,
    "lostopf": "Hanse/Meer/Küste/Deich",
    "latitude": 54.126998,
    "longitude": 8.858265,
    "latitude2": null,
    "longitude2": null
  },
  {
    "id": "HM-14",
    "bahnhof": null,
    "zeitbedarf": null,
    "distanz": null,
    "punkte_bahnhof": 85,
    "punkte_aufgabe": 0,
    "punkte_bonus": 0,
    "aufgabe": null,
    "lostopf": "Hanse/Meer/Küste/Deich",
    "latitude": 54.051919,
    "longitude": 10.753891,
    "latitude2": null,
    "longitude2": null
  },
  {
    "id": "HM-16",
    "bahnhof": null,
    "zeitbedarf": null,
    "distanz": null,
    "punkte_bahnhof": 86,
    "punkte_aufgabe": 0,
    "punkte_bonus": 0,
    "aufgabe": null,
    "lostopf": "Hanse/Meer/Küste/Deich",
    "latitude": 53.24917,
    "longitude": 10.41417,
    "latitude2": null,
    "longitude2": null
  },
  {
    "id": "HM-21",
    "bahnhof": null,
    "zeitbedarf": null,
    "distanz": null,
    "punkte_bahnhof": 87,
    "punkte_aufgabe": 0,
    "punkte_bonus": 0,
    "aufgabe": null,
    "lostopf": "Hanse/Meer/Küste/Deich",
    "latitude": 51.271363,
    "longitude": 8.872623,
    "latitude2": null,
    "longitude2": null
  },
  {
    "id": "HM-25",
    "bahnhof": null,
    "zeitbedarf": null,
    "distanz": null,
    "punkte_bahnhof": 88,
    "punkte_aufgabe": 0,
    "punkte_bonus": 0,
    "aufgabe": null,
    "lostopf": "Hanse/Meer/Küste/Deich",
    "latitude": 53.481878,
    "longitude": 8.488052,
    "latitude2": null,
    "longitude2": null
  },
  {
    "id": "MG-1",
    "bahnhof": null,
    "zeitbedarf": null,
    "distanz": null,
    "punkte_bahnhof": 89,
    "punkte_aufgabe": 0,
    "punkte_bonus": 0,
    "aufgabe": null,
    "lostopf": "Mini-Golf in Mini-Städten",
    "latitude": 51.556257,
    "longitude": 10.723233,
    "latitude2": null,
    "longitude2": null
  },
  {
    "id": "MG-2",
    "bahnhof": null,
    "zeitbedarf": null,
    "distanz": null,
    "punkte_bahnhof": 90,
    "punkte_aufgabe": 0,
    "punkte_bonus": 0,
    "aufgabe": null,
    "lostopf": "Mini-Golf in Mini-Städten",
    "latitude": 47.900777,
    "longitude": 8.152353,
    "latitude2": null,
    "longitude2": null
  },
  {
    "id": "MG-4",
    "bahnhof": null,
    "zeitbedarf": null,
    "distanz": null,
    "punkte_bahnhof": 91,
    "punkte_aufgabe": 0,
    "punkte_bonus": 0,
    "aufgabe": null,
    "lostopf": "Mini-Golf in Mini-Städten",
    "latitude": 53.999746,
    "longitude": 10.778266,
    "latitude2": null,
    "longitude2": null
  },
  {
    "id": "MG-6",
    "bahnhof": null,
    "zeitbedarf": null,
    "distanz": null,
    "punkte_bahnhof": 92,
    "punkte_aufgabe": 0,
    "punkte_bonus": 0,
    "aufgabe": null,
    "lostopf": "Mini-Golf in Mini-Städten",
    "latitude": 50.999127,
    "longitude": 8.117039,
    "latitude2": null,
    "longitude2": null
  },
  {
    "id": "MG-9",
    "bahnhof": null,
    "zeitbedarf": null,
    "distanz": null,
    "punkte_bahnhof": 93,
    "punkte_aufgabe": 0,
    "punkte_bonus": 0,
    "aufgabe": null,
    "lostopf": "Mini-Golf in Mini-Städten",
    "latitude": 51.289291,
    "longitude": 8.617026,
    "latitude2": null,
    "longitude2": null
  },
  {
    "id": "MG-16",
    "bahnhof": null,
    "zeitbedarf": null,
    "distanz": null,
    "punkte_bahnhof": 94,
    "punkte_aufgabe": 0,
    "punkte_bonus": 0,
    "aufgabe": null,
    "lostopf": "Mini-Golf in Mini-Städten",
    "latitude": 48.154733,
    "longitude": 8.045701,
    "latitude2": null,
    "longitude2": null
  },
  {
    "id": "MG-17",
    "bahnhof": null,
    "zeitbedarf": null,
    "distanz": null,
    "punkte_bahnhof": 95,
    "punkte_aufgabe": 0,
    "punkte_bonus": 0,
    "aufgabe": null,
    "lostopf": "Mini-Golf in Mini-Städten",
    "latitude": 51.741649,
    "longitude": 11.026719,
    "latitude2": null,
    "longitude2": null
  },
  {
    "id": "MG-18",
    "bahnhof": null,
    "zeitbedarf": null,
    "distanz": null,
    "punkte_bahnhof": 96,
    "punkte_aufgabe": 0,
    "punkte_bonus": 0,
    "aufgabe": null,
    "lostopf": "Mini-Golf in Mini-Städten",
    "latitude": 50.372934,
    "longitude": 8.011952,
    "latitude2": null,
    "longitude2": null
  },
  {
    "id": "MG-21",
    "bahnhof": null,
    "zeitbedarf": null,
    "distanz": null,
    "punkte_bahnhof": 97,
    "punkte_aufgabe": 0,
    "punkte_bonus": 0,
    "aufgabe": null,
    "lostopf": "Mini-Golf in Mini-Städten",
    "latitude": 52.15038,
    "longitude": 7.251984,
    "latitude2": null,
    "longitude2": null
  },
  {
    "id": "MG-25",
    "bahnhof": null,
    "zeitbedarf": null,
    "distanz": null,
    "punkte_bahnhof": 98,
    "punkte_aufgabe": 0,
    "punkte_bonus": 0,
    "aufgabe": null,
    "lostopf": "Mini-Golf in Mini-Städten",
    "latitude": 48.976542,
    "longitude": 9.663497,
    "latitude2": null,
    "longitude2": null
  },
  {
    "id": "M-2",
    "bahnhof": null,
    "zeitbedarf": null,
    "distanz": null,
    "punkte_bahnhof": 99,
    "punkte_aufgabe": 0,
    "punkte_bonus": 0,
    "aufgabe": null,
    "lostopf": "Münster Stadt & Umland/Fahrrad",
    "latitude": 51.967925,
    "longitude": 7.616883,
    "latitude2": null,
    "longitude2": null
  },
  {
    "id": "M-5",
    "bahnhof": null,
    "zeitbedarf": null,
    "distanz": null,
    "punkte_bahnhof": 100,
    "punkte_aufgabe": 0,
    "punkte_bonus": 0,
    "aufgabe": null,
    "lostopf": "Münster Stadt & Umland/Fahrrad",
    "latitude": 51.962954,
    "longitude": 7.628904,
    "latitude2": null,
    "longitude2": null
  },
  {
    "id": "M-9",
    "bahnhof": null,
    "zeitbedarf": null,
    "distanz": null,
    "punkte_bahnhof": 101,
    "punkte_aufgabe": 0,
    "punkte_bonus": 0,
    "aufgabe": null,
    "lostopf": "Münster Stadt & Umland/Fahrrad",
    "latitude": 51.911163,
    "longitude": 7.500201,
    "latitude2": null,
    "longitude2": null
  },
  {
    "id": "M-13",
    "bahnhof": null,
    "zeitbedarf": null,
    "distanz": null,
    "punkte_bahnhof": 102,
    "punkte_aufgabe": 0,
    "punkte_bonus": 0,
    "aufgabe": null,
    "lostopf": "Münster Stadt & Umland/Fahrrad",
    "latitude": 51.956476,
    "longitude": 7.629967,
    "latitude2": null,
    "longitude2": null
  },
  {
    "id": "M-14",
    "bahnhof": null,
    "zeitbedarf": null,
    "distanz": null,
    "punkte_bahnhof": 103,
    "punkte_aufgabe": 0,
    "punkte_bonus": 0,
    "aufgabe": null,
    "lostopf": "Münster Stadt & Umland/Fahrrad",
    "latitude": 51.96763,
    "longitude": 7.629557,
    "latitude2": null,
    "longitude2": null
  },
  {
    "id": "M-15",
    "bahnhof": null,
    "zeitbedarf": null,
    "distanz": null,
    "punkte_bahnhof": 104,
    "punkte_aufgabe": 0,
    "punkte_bonus": 0,
    "aufgabe": null,
    "lostopf": "Münster Stadt & Umland/Fahrrad",
    "latitude": 51.960249,
    "longitude": 7.626451,
    "latitude2": null,
    "longitude2": null
  },
  {
    "id": "M-19",
    "bahnhof": null,
    "zeitbedarf": null,
    "distanz": null,
    "punkte_bahnhof": 105,
    "punkte_aufgabe": 0,
    "punkte_bonus": 0,
    "aufgabe": null,
    "lostopf": "Münster Stadt & Umland/Fahrrad",
    "latitude": 51.985526,
    "longitude": 7.790336,
    "latitude2": null,
    "longitude2": null
  },
  {
    "id": "M-23",
    "bahnhof": null,
    "zeitbedarf": null,
    "distanz": null,
    "punkte_bahnhof": 106,
    "punkte_aufgabe": 0,
    "punkte_bonus": 0,
    "aufgabe": null,
    "lostopf": "Münster Stadt & Umland/Fahrrad",
    "latitude": 51.898162,
    "longitude": 7.421932,
    "latitude2": null,
    "longitude2": null
  },
  {
    "id": "M-24",
    "bahnhof": null,
    "zeitbedarf": null,
    "distanz": null,
    "punkte_bahnhof": 107,
    "punkte_aufgabe": 0,
    "punkte_bonus": 0,
    "aufgabe": null,
    "lostopf": "Münster Stadt & Umland/Fahrrad",
    "latitude": 51.96299,
    "longitude": 7.629862,
    "latitude2": null,
    "longitude2": null
  },
  {
    "id": "N-1",
    "bahnhof": "Seebrugg",
    "zeitbedarf": 17,
    "distanz": 0.5,
    "punkte_bahnhof": 119,
    "punkte_aufgabe": 30,
    "punkte_bonus": 0,
    "aufgabe": "Besucht die BSW Angler- und Wandergruppe, Foto mit Holzschild\nZiel des ehm. IC Seebrugg",
    "lostopf": "Natur/Wanderbahnhöfe",
    "latitude": 47.803516,
    "longitude": 8.191115,
    "latitude2": 47.801429,
    "longitude2": 8.196188
  },
  {
    "id": "N-3",
    "bahnhof": "Waltershausen Schnepfenthal",
    "zeitbedarf": 31,
    "distanz": 1.1,
    "punkte_bahnhof": 120,
    "punkte_aufgabe": 50,
    "punkte_bonus": 10,
    "aufgabe": "Bersuche das Waltershausen, Gleisdreieck; Bonus Bild mit Straßenbahn\n",
    "lostopf": "Natur/Wanderbahnhöfe",
    "latitude": 50.883974,
    "longitude": 10.576211,
    "latitude2": 50.889766,
    "longitude2": 10.577837
  },
  {
    "id": "N-5",
    "bahnhof": "Füssen Ziegelwies",
    "zeitbedarf": 41,
    "distanz": 1.3,
    "punkte_bahnhof": 121,
    "punkte_aufgabe": 65,
    "punkte_bonus": 0,
    "aufgabe": "Wandere zum Lechfall und fotografiere diesen von der Brücke aus\n",
    "lostopf": "Natur/Wanderbahnhöfe",
    "latitude": 47.561817,
    "longitude": 10.694816,
    "latitude2": null,
    "longitude2": null
  },
  {
    "id": "N-7",
    "bahnhof": "Ronneburg(Thür)",
    "zeitbedarf": 31,
    "distanz": 1,
    "punkte_bahnhof": 122,
    "punkte_aufgabe": 50,
    "punkte_bonus": 10,
    "aufgabe": "Wandere zur Erlebnisbrücke Drachenschwanz, gehe auf diese und fotografiert die Eisenbahnbrücke von dieser aus (Bonus Zug im Bild)\n",
    "lostopf": "Natur/Wanderbahnhöfe",
    "latitude": 50.859555,
    "longitude": 12.18172,
    "latitude2": 50.857474,
    "longitude2": 12.169759
  },
  {
    "id": "N-8",
    "bahnhof": "Thale Hbf",
    "zeitbedarf": 61,
    "distanz": 1.8,
    "punkte_bahnhof": 123,
    "punkte_aufgabe": 95,
    "punkte_bonus": 0,
    "aufgabe": "Wanderung zum Teufelswaschbecken und fotografiere dieses Highlight\nggf. googeln wie das Teufelswaschbecken aussieht",
    "lostopf": "Natur/Wanderbahnhöfe",
    "latitude": 51.746047,
    "longitude": 11.031048,
    "latitude2": 49.687662,
    "longitude2": 8.626577
  },
  {
    "id": "N-9",
    "bahnhof": "Berchtesgaden Hbf",
    "zeitbedarf": 61,
    "distanz": 1.6,
    "punkte_bahnhof": 124,
    "punkte_aufgabe": 95,
    "punkte_bonus": 0,
    "aufgabe": "Wandere zum Kalten Keller und macht ein Team Bild im Eingang\n",
    "lostopf": "Natur/Wanderbahnhöfe",
    "latitude": 47.626688,
    "longitude": 12.999058,
    "latitude2": 47.626569,
    "longitude2": 13.007641
  },
  {
    "id": "N-10",
    "bahnhof": "Donaueschingen",
    "zeitbedarf": 17,
    "distanz": 0.6,
    "punkte_bahnhof": 125,
    "punkte_aufgabe": 30,
    "punkte_bonus": 0,
    "aufgabe": "Macht ein Foto mit dem Team um die \"Donauquelle\"\nFoto am Ring unten erstellen",
    "lostopf": "Natur/Wanderbahnhöfe",
    "latitude": 47.947899,
    "longitude": 8.498788,
    "latitude2": 47.951845,
    "longitude2": 8.502506
  },
  {
    "id": "N-17",
    "bahnhof": null,
    "zeitbedarf": null,
    "distanz": null,
    "punkte_bahnhof": 126,
    "punkte_aufgabe": 0,
    "punkte_bonus": 0,
    "aufgabe": null,
    "lostopf": "Natur/Wanderbahnhöfe",
    "latitude": 53.0157,
    "longitude": 10.426253,
    "latitude2": null,
    "longitude2": null
  },
  {
    "id": "N-20",
    "bahnhof": null,
    "zeitbedarf": null,
    "distanz": null,
    "punkte_bahnhof": 127,
    "punkte_aufgabe": 0,
    "punkte_bonus": 0,
    "aufgabe": null,
    "lostopf": "Natur/Wanderbahnhöfe",
    "latitude": 48.888583,
    "longitude": 8.703743,
    "latitude2": null,
    "longitude2": null
  },
  {
    "id": "N-24",
    "bahnhof": null,
    "zeitbedarf": null,
    "distanz": null,
    "punkte_bahnhof": 128,
    "punkte_aufgabe": 0,
    "punkte_bonus": 0,
    "aufgabe": null,
    "lostopf": "Natur/Wanderbahnhöfe",
    "latitude": 50.631987,
    "longitude": 6.461743,
    "latitude2": null,
    "longitude2": null
  },
  {
    "id": "R-3",
    "bahnhof": null,
    "zeitbedarf": null,
    "distanz": null,
    "punkte_bahnhof": 129,
    "punkte_aufgabe": 0,
    "punkte_bonus": 0,
    "aufgabe": null,
    "lostopf": "Rangierbahnhöfe",
    "latitude": 52.289857,
    "longitude": 12.989335,
    "latitude2": null,
    "longitude2": null
  },
  {
    "id": "R-7",
    "bahnhof": null,
    "zeitbedarf": null,
    "distanz": null,
    "punkte_bahnhof": 131,
    "punkte_aufgabe": 0,
    "punkte_bonus": 0,
    "aufgabe": null,
    "lostopf": "Rangierbahnhöfe",
    "latitude": 51.211383,
    "longitude": 6.686205,
    "latitude2": null,
    "longitude2": null
  },
  {
    "id": "R-9",
    "bahnhof": null,
    "zeitbedarf": null,
    "distanz": null,
    "punkte_bahnhof": 132,
    "punkte_aufgabe": 0,
    "punkte_bonus": 0,
    "aufgabe": null,
    "lostopf": "Rangierbahnhöfe",
    "latitude": 49.248573,
    "longitude": 6.845999,
    "latitude2": null,
    "longitude2": null
  },
  {
    "id": "R-14",
    "bahnhof": null,
    "zeitbedarf": null,
    "distanz": null,
    "punkte_bahnhof": 133,
    "punkte_aufgabe": 0,
    "punkte_bonus": 0,
    "aufgabe": null,
    "lostopf": "Rangierbahnhöfe",
    "latitude": 51.482025,
    "longitude": 11.991181,
    "latitude2": null,
    "longitude2": null
  },
  {
    "id": "R-18",
    "bahnhof": null,
    "zeitbedarf": null,
    "distanz": null,
    "punkte_bahnhof": 134,
    "punkte_aufgabe": 0,
    "punkte_bonus": 0,
    "aufgabe": null,
    "lostopf": "Rangierbahnhöfe",
    "latitude": 50.966395,
    "longitude": 9.798999,
    "latitude2": null,
    "longitude2": null
  },
  {
    "id": "R-19",
    "bahnhof": null,
    "zeitbedarf": null,
    "distanz": null,
    "punkte_bahnhof": 135,
    "punkte_aufgabe": 0,
    "punkte_bonus": 0,
    "aufgabe": null,
    "lostopf": "Rangierbahnhöfe",
    "latitude": 49.986809,
    "longitude": 8.366186,
    "latitude2": null,
    "longitude2": null
  },
  {
    "id": "R-21",
    "bahnhof": null,
    "zeitbedarf": null,
    "distanz": null,
    "punkte_bahnhof": 136,
    "punkte_aufgabe": 0,
    "punkte_bonus": 0,
    "aufgabe": null,
    "lostopf": "Rangierbahnhöfe",
    "latitude": 51.390969,
    "longitude": 6.80213,
    "latitude2": null,
    "longitude2": null
  },
  {
    "id": "R-23",
    "bahnhof": null,
    "zeitbedarf": null,
    "distanz": null,
    "punkte_bahnhof": 137,
    "punkte_aufgabe": 0,
    "punkte_bonus": 0,
    "aufgabe": null,
    "lostopf": "Rangierbahnhöfe",
    "latitude": 49.454135,
    "longitude": 8.528916,
    "latitude2": null,
    "longitude2": null
  },
  {
    "id": "R-24",
    "bahnhof": null,
    "zeitbedarf": null,
    "distanz": null,
    "punkte_bahnhof": 138,
    "punkte_aufgabe": 0,
    "punkte_bonus": 0,
    "aufgabe": null,
    "lostopf": "Rangierbahnhöfe",
    "latitude": 52.392992,
    "longitude": 9.586046,
    "latitude2": null,
    "longitude2": null
  },
  {
    "id": "T-3",
    "bahnhof": null,
    "zeitbedarf": null,
    "distanz": null,
    "punkte_bahnhof": 139,
    "punkte_aufgabe": 0,
    "punkte_bonus": 0,
    "aufgabe": null,
    "lostopf": "Tatort",
    "latitude": 53.55683,
    "longitude": 10.005019,
    "latitude2": null,
    "longitude2": null
  },
  {
    "id": "T-4",
    "bahnhof": null,
    "zeitbedarf": null,
    "distanz": null,
    "punkte_bahnhof": 140,
    "punkte_aufgabe": 0,
    "punkte_bonus": 0,
    "aufgabe": null,
    "lostopf": "Tatort",
    "latitude": 50.070821,
    "longitude": 8.241747,
    "latitude2": null,
    "longitude2": null
  },
  {
    "id": "T-5",
    "bahnhof": null,
    "zeitbedarf": null,
    "distanz": null,
    "punkte_bahnhof": 141,
    "punkte_aufgabe": 0,
    "punkte_bonus": 0,
    "aufgabe": null,
    "lostopf": "Tatort",
    "latitude": 50.367841,
    "longitude": 8.748345,
    "latitude2": null,
    "longitude2": null
  },
  {
    "id": "T-10",
    "bahnhof": null,
    "zeitbedarf": null,
    "distanz": null,
    "punkte_bahnhof": 142,
    "punkte_aufgabe": 0,
    "punkte_bonus": 0,
    "aufgabe": null,
    "lostopf": "Tatort",
    "latitude": 50.771626,
    "longitude": 6.551073,
    "latitude2": null,
    "longitude2": null
  },
  {
    "id": "T-14",
    "bahnhof": null,
    "zeitbedarf": null,
    "distanz": null,
    "punkte_bahnhof": 143,
    "punkte_aufgabe": 0,
    "punkte_bonus": 0,
    "aufgabe": null,
    "lostopf": "Tatort",
    "latitude": 50.109909,
    "longitude": 8.658953,
    "latitude2": null,
    "longitude2": null
  },
  {
    "id": "T-16",
    "bahnhof": null,
    "zeitbedarf": null,
    "distanz": null,
    "punkte_bahnhof": 144,
    "punkte_aufgabe": 0,
    "punkte_bonus": 0,
    "aufgabe": null,
    "lostopf": "Tatort",
    "latitude": 50.944972,
    "longitude": 6.898263,
    "latitude2": null,
    "longitude2": null
  },
  {
    "id": "T-20",
    "bahnhof": null,
    "zeitbedarf": null,
    "distanz": null,
    "punkte_bahnhof": 145,
    "punkte_aufgabe": 0,
    "punkte_bonus": 0,
    "aufgabe": null,
    "lostopf": "Tatort",
    "latitude": 50.978878,
    "longitude": 11.031253,
    "latitude2": null,
    "longitude2": null
  },
  {
    "id": "T-21",
    "bahnhof": null,
    "zeitbedarf": null,
    "distanz": null,
    "punkte_bahnhof": 146,
    "punkte_aufgabe": 0,
    "punkte_bonus": 0,
    "aufgabe": null,
    "lostopf": "Tatort",
    "latitude": 49.478088,
    "longitude": 8.448842,
    "latitude2": null,
    "longitude2": null
  },
  {
    "id": "T-22",
    "bahnhof": null,
    "zeitbedarf": null,
    "distanz": null,
    "punkte_bahnhof": 147,
    "punkte_aufgabe": 0,
    "punkte_bonus": 0,
    "aufgabe": null,
    "lostopf": "Tatort",
    "latitude": 50.732541,
    "longitude": 7.085292,
    "latitude2": null,
    "longitude2": null
  },
  {
    "id": "B-4",
    "bahnhof": null,
    "zeitbedarf": null,
    "distanz": null,
    "punkte_bahnhof": 149,
    "punkte_aufgabe": 0,
    "punkte_bonus": 0,
    "aufgabe": null,
    "lostopf": "Turm/Insel/Keil/Kopf-Bahnhöfe",
    "latitude": 51.22652,
    "longitude": 9.46901,
    "latitude2": null,
    "longitude2": null
  },
  {
    "id": "B-9",
    "bahnhof": null,
    "zeitbedarf": null,
    "distanz": null,
    "punkte_bahnhof": 150,
    "punkte_aufgabe": 0,
    "punkte_bonus": 0,
    "aufgabe": null,
    "lostopf": "Turm/Insel/Keil/Kopf-Bahnhöfe",
    "latitude": 50.581109,
    "longitude": 8.665803,
    "latitude2": null,
    "longitude2": null
  },
  {
    "id": "B-11",
    "bahnhof": null,
    "zeitbedarf": null,
    "distanz": null,
    "punkte_bahnhof": 151,
    "punkte_aufgabe": 0,
    "punkte_bonus": 0,
    "aufgabe": null,
    "lostopf": "Turm/Insel/Keil/Kopf-Bahnhöfe",
    "latitude": 52.564861,
    "longitude": 14.405309,
    "latitude2": null,
    "longitude2": null
  },
  {
    "id": "B-14",
    "bahnhof": null,
    "zeitbedarf": null,
    "distanz": null,
    "punkte_bahnhof": 152,
    "punkte_aufgabe": 0,
    "punkte_bonus": 0,
    "aufgabe": null,
    "lostopf": "Turm/Insel/Keil/Kopf-Bahnhöfe",
    "latitude": 51.614409,
    "longitude": 7.522341,
    "latitude2": null,
    "longitude2": null
  },
  {
    "id": "B-18",
    "bahnhof": null,
    "zeitbedarf": null,
    "distanz": null,
    "punkte_bahnhof": 153,
    "punkte_aufgabe": 0,
    "punkte_bonus": 0,
    "aufgabe": null,
    "lostopf": "Turm/Insel/Keil/Kopf-Bahnhöfe",
    "latitude": 51.7653,
    "longitude": 8.92921,
    "latitude2": null,
    "longitude2": null
  },
  {
    "id": "B-19",
    "bahnhof": null,
    "zeitbedarf": null,
    "distanz": null,
    "punkte_bahnhof": 154,
    "punkte_aufgabe": 0,
    "punkte_bonus": 0,
    "aufgabe": null,
    "lostopf": "Turm/Insel/Keil/Kopf-Bahnhöfe",
    "latitude": 50.570929,
    "longitude": 12.235387,
    "latitude2": null,
    "longitude2": null
  },
  {
    "id": "B-21",
    "bahnhof": null,
    "zeitbedarf": null,
    "distanz": null,
    "punkte_bahnhof": 155,
    "punkte_aufgabe": 0,
    "punkte_bonus": 0,
    "aufgabe": null,
    "lostopf": "Turm/Insel/Keil/Kopf-Bahnhöfe",
    "latitude": 51.513522,
    "longitude": 7.418741,
    "latitude2": null,
    "longitude2": null
  },
  {
    "id": "B-22",
    "bahnhof": null,
    "zeitbedarf": null,
    "distanz": null,
    "punkte_bahnhof": 156,
    "punkte_aufgabe": 0,
    "punkte_bonus": 0,
    "aufgabe": null,
    "lostopf": "Turm/Insel/Keil/Kopf-Bahnhöfe",
    "latitude": 49.645661,
    "longitude": 8.457419,
    "latitude2": null,
    "longitude2": null
  },
  {
    "id": "B-23",
    "bahnhof": null,
    "zeitbedarf": null,
    "distanz": null,
    "punkte_bahnhof": 157,
    "punkte_aufgabe": 0,
    "punkte_bonus": 0,
    "aufgabe": null,
    "lostopf": "Turm/Insel/Keil/Kopf-Bahnhöfe",
    "latitude": 51.829214,
    "longitude": 7.276327,
    "latitude2": null,
    "longitude2": null
  },
  {
    "id": "B-24",
    "bahnhof": null,
    "zeitbedarf": null,
    "distanz": null,
    "punkte_bahnhof": 158,
    "punkte_aufgabe": 0,
    "punkte_bonus": 0,
    "aufgabe": null,
    "lostopf": "Turm/Insel/Keil/Kopf-Bahnhöfe",
    "latitude": 52.271668,
    "longitude": 8.05723,
    "latitude2": null,
    "longitude2": null
  },
  {
    "id": "U-2",
    "bahnhof": null,
    "zeitbedarf": null,
    "distanz": null,
    "punkte_bahnhof": 159,
    "punkte_aufgabe": 0,
    "punkte_bonus": 0,
    "aufgabe": null,
    "lostopf": "Unter Tage",
    "latitude": 50.586438,
    "longitude": 6.649587,
    "latitude2": null,
    "longitude2": null
  },
  {
    "id": "U-4",
    "bahnhof": null,
    "zeitbedarf": null,
    "distanz": null,
    "punkte_bahnhof": 160,
    "punkte_aufgabe": 0,
    "punkte_bonus": 0,
    "aufgabe": null,
    "lostopf": "Unter Tage",
    "latitude": 50.087694,
    "longitude": 7.763732,
    "latitude2": null,
    "longitude2": null
  },
  {
    "id": "U-10",
    "bahnhof": null,
    "zeitbedarf": null,
    "distanz": null,
    "punkte_bahnhof": 161,
    "punkte_aufgabe": 0,
    "punkte_bonus": 0,
    "aufgabe": null,
    "lostopf": "Unter Tage",
    "latitude": 48.860784,
    "longitude": 10.103166,
    "latitude2": null,
    "longitude2": null
  },
  {
    "id": "U-14",
    "bahnhof": null,
    "zeitbedarf": null,
    "distanz": null,
    "punkte_bahnhof": 162,
    "punkte_aufgabe": 0,
    "punkte_bonus": 0,
    "aufgabe": null,
    "lostopf": "Unter Tage",
    "latitude": 51.417126,
    "longitude": 7.074189,
    "latitude2": null,
    "longitude2": null
  },
  {
    "id": "U-15",
    "bahnhof": null,
    "zeitbedarf": null,
    "distanz": null,
    "punkte_bahnhof": 163,
    "punkte_aufgabe": 0,
    "punkte_bonus": 0,
    "aufgabe": null,
    "lostopf": "Unter Tage",
    "latitude": 50.377976,
    "longitude": 7.284691,
    "latitude2": null,
    "longitude2": null
  },
  {
    "id": "U-16",
    "bahnhof": null,
    "zeitbedarf": null,
    "distanz": null,
    "punkte_bahnhof": 164,
    "punkte_aufgabe": 0,
    "punkte_bonus": 0,
    "aufgabe": null,
    "lostopf": "Unter Tage",
    "latitude": 52.299185,
    "longitude": 9.470303,
    "latitude2": null,
    "longitude2": null
  },
  {
    "id": "U-18",
    "bahnhof": null,
    "zeitbedarf": null,
    "distanz": null,
    "punkte_bahnhof": 165,
    "punkte_aufgabe": 0,
    "punkte_bonus": 0,
    "aufgabe": null,
    "lostopf": "Unter Tage",
    "latitude": 50.004014,
    "longitude": 8.263958,
    "latitude2": null,
    "longitude2": null
  },
  {
    "id": "U-22",
    "bahnhof": null,
    "zeitbedarf": null,
    "distanz": null,
    "punkte_bahnhof": 166,
    "punkte_aufgabe": 0,
    "punkte_bonus": 0,
    "aufgabe": null,
    "lostopf": "Unter Tage",
    "latitude": 51.091737,
    "longitude": 6.459103,
    "latitude2": null,
    "longitude2": null
  },
  {
    "id": "U-23",
    "bahnhof": null,
    "zeitbedarf": null,
    "distanz": null,
    "punkte_bahnhof": 167,
    "punkte_aufgabe": 0,
    "punkte_bonus": 0,
    "aufgabe": null,
    "lostopf": "Unter Tage",
    "latitude": 51.429008,
    "longitude": 7.313015,
    "latitude2": null,
    "longitude2": null
  },
  {
    "id": "U-24",
    "bahnhof": null,
    "zeitbedarf": null,
    "distanz": null,
    "punkte_bahnhof": 168,
    "punkte_aufgabe": 0,
    "punkte_bonus": 0,
    "aufgabe": null,
    "lostopf": "Unter Tage",
    "latitude": 50.885672,
    "longitude": 11.790006,
    "latitude2": null,
    "longitude2": null
  },
  {
    "id": "WK-2",
    "bahnhof": "Potsdam-Babelsberg",
    "zeitbedarf": 61,
    "distanz": 2.1,
    "punkte_bahnhof": 169,
    "punkte_aufgabe": 95,
    "punkte_bonus": 20,
    "aufgabe": "Mache ein Foto vor der Blumenfontäne von Fürst Pückler. Bonus mit Pückler Eis.\n",
    "lostopf": "Weltkulturerbe",
    "latitude": 52.391391,
    "longitude": 13.092871,
    "latitude2": 52.404486,
    "longitude2": 13.0949
  },
  {
    "id": "WK-4",
    "bahnhof": "Lutherstadt Eisleben",
    "zeitbedarf": 47,
    "distanz": 1.6,
    "punkte_bahnhof": 170,
    "punkte_aufgabe": 75,
    "punkte_bonus": null,
    "aufgabe": "Mach ein Foto vor dem Lutherdenkmal in Eisleben.\n",
    "lostopf": "Weltkulturerbe",
    "latitude": 51.518314,
    "longitude": 11.55088,
    "latitude2": 51.528354,
    "longitude2": 11.546315
  },
  {
    "id": "WK-5",
    "bahnhof": "Bamberg Bahnhof",
    "zeitbedarf": 41,
    "distanz": 1.2,
    "punkte_bahnhof": 171,
    "punkte_aufgabe": 65,
    "punkte_bonus": null,
    "aufgabe": "Trink ein Rauchbier in der Altstadt vom Bamberg.\n",
    "lostopf": "Weltkulturerbe",
    "latitude": 49.891729,
    "longitude": 10.887108,
    "latitude2": null,
    "longitude2": null
  },
  {
    "id": "WK-6",
    "bahnhof": "Völklingen",
    "zeitbedarf": 17,
    "distanz": 0.35,
    "punkte_bahnhof": 172,
    "punkte_aufgabe": 30,
    "punkte_bonus": 20,
    "aufgabe": "Foto vor dem Haupteingang der Völklinger Hütte. Bonus: Iss etwas aus dem lokalen Shop.\n",
    "lostopf": "Weltkulturerbe",
    "latitude": 49.249091,
    "longitude": 6.848156,
    "latitude2": 49.248462,
    "longitude2": 6.844351
  },
  {
    "id": "WK-9",
    "bahnhof": "Maulbronn Stadt/Kloster",
    "zeitbedarf": 37,
    "distanz": 1,
    "punkte_bahnhof": 173,
    "punkte_aufgabe": 60,
    "punkte_bonus": null,
    "aufgabe": "mach ein Foto von der Stauferstele Maulbronn\n",
    "lostopf": "Weltkulturerbe",
    "latitude": 48.996933,
    "longitude": 8.803726,
    "latitude2": 49.000736,
    "longitude2": 8.813832
  },
  {
    "id": "WK-13",
    "bahnhof": "Bremen Hbf",
    "zeitbedarf": 61,
    "distanz": 1.2,
    "punkte_bahnhof": 174,
    "punkte_aufgabe": 95,
    "punkte_bonus": null,
    "aufgabe": "Mach ein Foto mit den Bremer Stadtmusikaten\n",
    "lostopf": "Weltkulturerbe",
    "latitude": 53.083481,
    "longitude": 8.813834,
    "latitude2": null,
    "longitude2": null
  },
  {
    "id": "WK-14",
    "bahnhof": "Hamburg Stadthausbrücke",
    "zeitbedarf": 61,
    "distanz": 1.8,
    "punkte_bahnhof": 175,
    "punkte_aufgabe": 95,
    "punkte_bonus": null,
    "aufgabe": "Mach ein Bild vor dem Miniaturwunderland\n",
    "lostopf": "Weltkulturerbe",
    "latitude": 53.549465,
    "longitude": 9.984804,
    "latitude2": 53.543747,
    "longitude2": 9.989112
  },
  {
    "id": "WK-15",
    "bahnhof": null,
    "zeitbedarf": null,
    "distanz": null,
    "punkte_bahnhof": 176,
    "punkte_aufgabe": 0,
    "punkte_bonus": 0,
    "aufgabe": null,
    "lostopf": "Weltkulturerbe",
    "latitude": 51.31316,
    "longitude": 9.44579,
    "latitude2": null,
    "longitude2": null
  },
  {
    "id": "WK-23",
    "bahnhof": null,
    "zeitbedarf": null,
    "distanz": null,
    "punkte_bahnhof": 177,
    "punkte_aufgabe": 0,
    "punkte_bonus": 0,
    "aufgabe": null,
    "lostopf": "Weltkulturerbe",
    "latitude": 50.774844,
    "longitude": 6.083981,
    "latitude2": null,
    "longitude2": null
  },
  {
    "id": "WK-24",
    "bahnhof": null,
    "zeitbedarf": null,
    "distanz": null,
    "punkte_bahnhof": 178,
    "punkte_aufgabe": 0,
    "punkte_bonus": 0,
    "aufgabe": null,
    "lostopf": "Weltkulturerbe",
    "latitude": 53.866159,
    "longitude": 10.67968,
    "latitude2": null,
    "longitude2": null
  },
  {
    "id": "W-1",
    "bahnhof": null,
    "zeitbedarf": null,
    "distanz": null,
    "punkte_bahnhof": 179,
    "punkte_aufgabe": 0,
    "punkte_bonus": 0,
    "aufgabe": null,
    "lostopf": "Wunschlos",
    "latitude": 54.107738,
    "longitude": 10.814871,
    "latitude2": null,
    "longitude2": null
  },
  {
    "id": "W-3",
    "bahnhof": null,
    "zeitbedarf": null,
    "distanz": null,
    "punkte_bahnhof": 180,
    "punkte_aufgabe": 0,
    "punkte_bonus": 0,
    "aufgabe": null,
    "lostopf": "Wunschlos",
    "latitude": 53.47695,
    "longitude": 9.702181,
    "latitude2": null,
    "longitude2": null
  },
  {
    "id": "W-4",
    "bahnhof": null,
    "zeitbedarf": null,
    "distanz": null,
    "punkte_bahnhof": 181,
    "punkte_aufgabe": 0,
    "punkte_bonus": 0,
    "aufgabe": null,
    "lostopf": "Wunschlos",
    "latitude": 53.961976,
    "longitude": 10.889142,
    "latitude2": null,
    "longitude2": null
  },
  {
    "id": "W-6",
    "bahnhof": null,
    "zeitbedarf": null,
    "distanz": null,
    "punkte_bahnhof": 182,
    "punkte_aufgabe": 0,
    "punkte_bonus": 0,
    "aufgabe": null,
    "lostopf": "Wunschlos",
    "latitude": 51.402474,
    "longitude": 7.007615,
    "latitude2": null,
    "longitude2": null
  },
  {
    "id": "W-7",
    "bahnhof": null,
    "zeitbedarf": null,
    "distanz": null,
    "punkte_bahnhof": 183,
    "punkte_aufgabe": 0,
    "punkte_bonus": 0,
    "aufgabe": null,
    "lostopf": "Wunschlos",
    "latitude": 51.725038,
    "longitude": 7.612696,
    "latitude2": null,
    "longitude2": null
  },
  {
    "id": "W-8",
    "bahnhof": null,
    "zeitbedarf": null,
    "distanz": null,
    "punkte_bahnhof": 184,
    "punkte_aufgabe": 0,
    "punkte_bonus": 0,
    "aufgabe": null,
    "lostopf": "Wunschlos",
    "latitude": 50.438174,
    "longitude": 7.400095,
    "latitude2": null,
    "longitude2": null
  },
  {
    "id": "W-11",
    "bahnhof": null,
    "zeitbedarf": null,
    "distanz": null,
    "punkte_bahnhof": 185,
    "punkte_aufgabe": 0,
    "punkte_bonus": 0,
    "aufgabe": null,
    "lostopf": "Wunschlos",
    "latitude": 48.792241,
    "longitude": 9.229635,
    "latitude2": null,
    "longitude2": null
  },
  {
    "id": "W-13",
    "bahnhof": null,
    "zeitbedarf": null,
    "distanz": null,
    "punkte_bahnhof": 186,
    "punkte_aufgabe": 0,
    "punkte_bonus": 0,
    "aufgabe": null,
    "lostopf": "Wunschlos",
    "latitude": 49.968539,
    "longitude": 7.884273,
    "latitude2": null,
    "longitude2": null
  },
  {
    "id": "W-20",
    "bahnhof": null,
    "zeitbedarf": null,
    "distanz": null,
    "punkte_bahnhof": 187,
    "punkte_aufgabe": 0,
    "punkte_bonus": 0,
    "aufgabe": null,
    "lostopf": "Wunschlos",
    "latitude": 54.306169,
    "longitude": 9.662156,
    "latitude2": null,
    "longitude2": null
  },
  {
    "id": "W-21",
    "bahnhof": null,
    "zeitbedarf": null,
    "distanz": null,
    "punkte_bahnhof": 188,
    "punkte_aufgabe": 0,
    "punkte_bonus": 0,
    "aufgabe": null,
    "lostopf": "Wunschlos",
    "latitude": 50.323079,
    "longitude": 10.215723,
    "latitude2": null,
    "longitude2": null
  },
  {
    "id": "K-1",
    "bahnhof": "Aha",
    "zeitbedarf": 11,
    "distanz": 0.3,
    "punkte_bahnhof": 189,
    "punkte_aufgabe": 20,
    "punkte_bonus": null,
    "aufgabe": "Macht ein Gruppenbild am Schiffsanleger des Schluchsee (See im Hintergrund)\n",
    "lostopf": "Kranke Ortsnamen",
    "latitude": 47.833224,
    "longitude": 8.134349,
    "latitude2": 47.833079,
    "longitude2": 8.132605
  },
  {
    "id": "K-2",
    "bahnhof": "Alpen",
    "zeitbedarf": 27,
    "distanz": 0.9,
    "punkte_bahnhof": 190,
    "punkte_aufgabe": 45,
    "punkte_bonus": null,
    "aufgabe": "Macht ein Bild vor der Alpener Motte\n(ehemalige hölzerne Burg)",
    "lostopf": "Kranke Ortsnamen",
    "latitude": 51.583392,
    "longitude": 6.518041,
    "latitude2": 51.578496,
    "longitude2": 6.517964
  },
  {
    "id": "K-5",
    "bahnhof": "Oschatz",
    "zeitbedarf": 7,
    "distanz": 0.1,
    "punkte_bahnhof": 191,
    "punkte_aufgabe": 15,
    "punkte_bonus": null,
    "aufgabe": "Mache ein Bild vom Schmalspurbahnhof (Döllnitztalbahn)\n",
    "lostopf": "Kranke Ortsnamen",
    "latitude": 51.31174,
    "longitude": 13.104056,
    "latitude2": 51.311298,
    "longitude2": 13.10508
  },
  {
    "id": "K-7",
    "bahnhof": "Simmelsdorf-Hüttenbach",
    "zeitbedarf": 9,
    "distanz": 0.3,
    "punkte_bahnhof": 192,
    "punkte_aufgabe": 15,
    "punkte_bonus": 15,
    "aufgabe": "Mache ein Bld am EAST-END Dirtpark & Pumptrack. Bonus: Ein Fahrradfahrer ist im Bild\n",
    "lostopf": "Kranke Ortsnamen",
    "latitude": 49.598459,
    "longitude": 11.341671,
    "latitude2": 49.60078,
    "longitude2": 11.343457
  },
  {
    "id": "K-8",
    "bahnhof": "Sulzbach-Rosenberg",
    "zeitbedarf": 31,
    "distanz": 0.95,
    "punkte_bahnhof": 193,
    "punkte_aufgabe": 50,
    "punkte_bonus": null,
    "aufgabe": "Mache ein Bild vom Sulzbacher Schloss\n",
    "lostopf": "Kranke Ortsnamen",
    "latitude": 49.499478,
    "longitude": 11.739277,
    "latitude2": 49.505299,
    "longitude2": 11.73605
  },
  {
    "id": "K-10",
    "bahnhof": "Geilenkirchen",
    "zeitbedarf": 11,
    "distanz": 0.35,
    "punkte_bahnhof": 194,
    "punkte_aufgabe": 20,
    "punkte_bonus": null,
    "aufgabe": "Mache ein Bild am Brunnen Friedlandplatz\n",
    "lostopf": "Kranke Ortsnamen",
    "latitude": 50.961039,
    "longitude": 6.124518,
    "latitude2": 50.962797,
    "longitude2": 6.122523
  },
  {
    "id": "K-11",
    "bahnhof": "Güterglück",
    "zeitbedarf": 7,
    "distanz": 0.2,
    "punkte_bahnhof": 195,
    "punkte_aufgabe": 15,
    "punkte_bonus": null,
    "aufgabe": "macht ein Bild von der Eisenbahnüberführung im Ort (mit Bahnübergangsschild im Hintergrund)\nerst 2004 stillgelegter Abschnitt der Wetzlarer Bahn",
    "lostopf": "Kranke Ortsnamen",
    "latitude": 51.993474,
    "longitude": 11.986389,
    "latitude2": 51.992756,
    "longitude2": 11.985386
  },
  {
    "id": "K-12",
    "bahnhof": "Quadrath-Ichendorf",
    "zeitbedarf": 23,
    "distanz": 0.85,
    "punkte_bahnhof": 196,
    "punkte_aufgabe": 40,
    "punkte_bonus": null,
    "aufgabe": "macht ein Bild von der historischen Brikettpresse\n",
    "lostopf": "Kranke Ortsnamen",
    "latitude": 50.937777,
    "longitude": 6.686533,
    "latitude2": 50.936611,
    "longitude2": 6.695878
  },
  {
    "id": "K-17",
    "bahnhof": "Bengel",
    "zeitbedarf": 17,
    "distanz": 0.35,
    "punkte_bahnhof": 197,
    "punkte_aufgabe": 30,
    "punkte_bonus": 10,
    "aufgabe": "Macht ein Gruppenfoto vor der Wassertretanlage Bengel, Bonus: Gruppenfoto mit Füßen im Wasser\nÖffnungszeiten tgl. 9-17 Uhr",
    "lostopf": "Kranke Ortsnamen",
    "latitude": 50.010379,
    "longitude": 7.05803,
    "latitude2": 50.01214,
    "longitude2": 7.061291
  },
  {
    "id": "K-23",
    "bahnhof": null,
    "zeitbedarf": null,
    "distanz": null,
    "punkte_bahnhof": 198,
    "punkte_aufgabe": 0,
    "punkte_bonus": 0,
    "aufgabe": null,
    "lostopf": "Kranke Ortsnamen",
    "latitude": 50.304875,
    "longitude": 9.625067,
    "latitude2": null,
    "longitude2": null
  }
];

const bhfPaarLines = [
  [
    [
      51.643861,
      10.329923
    ],
    [
      49.872002,
      8.34281
    ]
  ],
  [
    [
      49.471494,
      11.200442
    ],
    [
      49.032686,
      7.999224
    ]
  ],
  [
    [
      49.436253,
      7.768677
    ],
    [
      50.177917,
      8.46898
    ]
  ],
  [
    [
      51.042262,
      14.480583
    ],
    [
      52.435672,
      13.540246
    ]
  ],
  [
    [
      51.477188,
      11.987518
    ],
    [
      52.057227,
      8.35771
    ]
  ],
  [
    [
      52.969922,
      10.552857
    ],
    [
      48.710222,
      9.41626
    ]
  ],
  [
    [
      53.911237,
      10.734885
    ],
    [
      51.217327,
      6.629644
    ]
  ],
  [
    [
      49.011672,
      12.099617
    ],
    [
      50.355078,
      11.168848
    ]
  ]
];

const partnerCityLines = [
  [
    [
      49.454213,
      11.070849
    ],
    [
      50.883063,
      12.057639
    ]
  ],
  [
    [
      54.193438,
      9.10093
    ],
    [
      53.856027,
      13.701789
    ]
  ],
  [
    [
      51.054434,
      8.78942
    ],
    [
      50.9112,
      13.043289
    ]
  ],
  [
    [
      53.002456,
      11.762482
    ],
    [
      53.75453,
      9.659152
    ]
  ],
  [
    [
      50.835115,
      10.951666
    ],
    [
      51.311971,
      9.448129
    ]
  ]
];
